# Generated by Django 5.0.2 on 2025-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.JSONField(blank=True, null=True, verbose_name='职位标签'),
        ),
    ]
